### PR TITLE
Add benchmark setup

### LINKED ISSUE #10: Add benchmarks
It'd be great to have some benchmarks to run against new PRs etc. Maybe we could leverage Next.js' [next-stats-action](https://github.com/vercel/next.js/tree/canary/.github/actions/next-stats-action) for this?

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes #10 

Adds Benchmarks using [benchmark.js](https://benchmarkjs.com) and a CI step based on [github-action-benchmark](https://github.com/rhysd/github-action-benchmark) (see https://github.com/blitz-js/superjson/issues/10#issuecomment-662625454).

### CODE REVIEW

**Comment by Skn0tt** [comment]
@merelinguist what do you think, should we setup benchmark [Charts](https://github.com/rhysd/github-action-benchmark#screenshots) or are regression alert comments sufficient?

**Comment by Skn0tt** [comment]
(#26 needs to be merged before this)

**Comment by merelinguist** [comment]
@Skn0tt I think the alerts is enough

**Comment by Skn0tt** [comment]
Alright! Then this should be working I suppose.

**Pull request merged**
