### PR TITLE
Add support for custom serialisers

### PR DESCRIPTION
**Pull request by Skn0tt**
Related to #69 

This PR allows users to supply their own, custom serialisers.

For MongoDB's ObjectIDs, this can be used like the following:

```ts
import SuperJSON from "superjson";
import { ObjectID } from "mongodb";

// this needs to be executed both on client and server
SuperJSON.registerCustom<ObjectID, string>(
  {
    isApplicable: (v): v is ObjectID => v instanceof ObjectID,
    serialize: v => v.toHexString(),
    deserialize: v => new ObjectID(v),
  },
  'objectid'
);

// ...

SuperJSON.serialise({ a: new ObjectID(), ... })
```

### CODE REVIEW

**Comment by Skn0tt** [comment]
@jorisre feel free to review! :D

**Review by jorisre — APPROVED** [review]
Looks good to me

Thanks for this feature :)

**Comment by italodeandra** [comment]
`mongodb` can't be imported on the client. Can you give me a light on how do I make this work with NextJS?

**Comment by italodeandra** [comment]
> `mongodb` can't be imported on the client. Can you give me a light on how do I make this work with NextJS?

I fixed it. Instead of importing from `mongodb` you should import from `bson`.

```ts
import { ObjectID } from "bson";
```

`bson` is a peer dependency from the `mongodb` driver and is where the **ObjectId** is from.

I think it would be a good idea to update your example and add an explanation.

**Comment by oxdev03** [comment]
Find out another way for one way serialization without importing any dependencies

import SuperJSON from "superjson";
import type { ObjectId } from "bson";

```ts
/**
 * Registers a custom serialization for ObjectId without importing addtional dependencies
 */
SuperJSON.registerCustom<ObjectId, string>(
  {
    isApplicable: (v): v is ObjectId => v?._bsontype && v?._bsontype == "ObjectId",
    serialize: (v) => v.toHexString(),
    deserialize: (v) => v as any,
  },
  "ObjectId",
);
```

**Pull request merged**
