### PR TITLE
Don't mutate deserialized object

### PR DESCRIPTION
**Pull request by Skn0tt**
Closes https://github.com/blitz-js/babel-plugin-superjson-next/issues/63

### CODE REVIEW

**Comment by Skn0tt** [comment]
@PeterDekkers I've published this under the `danger` tag. Could you verify that `npm i superjson@danger` resolves the issue for you?

**Comment by PeterDekkers** [comment]
@Skn0tt that works a treat. Thank you!

**Comment by Skn0tt** [comment]
@allcontributors please add @PeterDekkers for bug

**Comment by Skn0tt** [comment]
Published in [v1.7.4](https://github.com/blitz-js/superjson/releases/tag/v1.7.4)

**Pull request merged**
