### PR TITLE
fix(src/index): export `stringify` function

### LINKED ISSUE #177: Export `stringify` separately
It seems like the Typescript definition for `superjson` only exports the `stringify` method as a properly of the default export:

```typescript
import { SuperJSONResult, SuperJSONValue, Class, JSONValue } from './types';
import { RegisterOptions } from './class-registry';
import { CustomTransfomer } from './custom-transformer-registry';
export declare const serialize: (object: SuperJSONValue) => SuperJSONResult;
export declare const deserialize: <T = unknown>(payload: SuperJSONResult) => T;
export declare const parse: <T = unknown>(string: string) => T;
declare const _default: {
    stringify: (object: any) => string;
    parse: <T = unknown>(string: string) => T;
    serialize: (object: any) => SuperJSONResult;
    deserialize: <T_1 = unknown>(payload: SuperJSONResult) => T_1;
    registerClass: (v: Class, options?: string | RegisterOptions | undefined) => void;
    registerSymbol: (v: Symbol, identifier?: string | undefined) => void;
    registerCustom: <I, O extends JSONValue>(transformer: Omit<CustomTransfomer<I, O>, "name">, name: string) => void;
    allowErrorProps: (...props: string[]) => void;
};
export default _default;
```
Because of this, I can't:
```typescript
import { parse, stringify } from 'superjson';
```
Because `parse` is exported but `stringify` isn't. And I've got no idea why it isn't.

### PR DESCRIPTION
**Pull request by nicholaschiang**
Fixes #177

### CODE REVIEW

**Comment by Skn0tt** [comment]
@all-contributors add @nicholaschiang for bug, code

**Comment by CoolOppo** [comment]
when will this be on NPM?

**Comment by Skn0tt** [comment]
uh - give me a minute, forgot to release :D

**Comment by Skn0tt** [comment]
published in v1.8.2

**Comment by CoolOppo** [comment]
wow that was fast lol

**Pull request merged**
