### PR TITLE
Add NaN and +/-Infinity tests

### PR DESCRIPTION
**Pull request by MrLeebo**
- NaN and Infinity are of type `number` but aren't naturally serializable as JSON

### CODE REVIEW

**Comment by Skn0tt** [comment]
If we added `nan` and `infinity` as meta types instead of `number`, we could spare to include it in the `values`. I suppose that could save some bytes

**Comment by MrLeebo** [comment]
Hey @Skn0tt,

I'm afraid I don't understand. By "values" are you referring to `type JSONValue`?  Why would we give them custom meta types when "number" is their actual type?

**Comment by Skn0tt** [comment]
Sorry, I guess I could have made that clearer ^^ At the moment, an object `{ a: NaN }` is serialised to `{ values: { a: "NaN" }, meta: { a: "number" } }`. That's 8 characters for `a: "NaN"`, right?
I propose to serialise it to `{ values: {}, meta: { a: "NaN" } }` instead. That'd save the 8 characters.
The same goes for `Infinity`.

Also, @flybayer's comment applies: https://github.com/blitz-js/superjson/pull/6#discussion_r454422032

**Comment by MrLeebo** [comment]
Made the suggested revisions. I guess if we wanted to be even more condensed we could replace the words, e.g. "Infinity", with symbols like "∞"

**Comment by Skn0tt** [comment]
Awesome! Thanks a lot :) I'll go forward and merge then :)

**Pull request merged**
