### PR TITLE
Support for decimal.js. Support for Prisma.Decimal.

### LINKED ISSUE #152: issue with Next.js Decimal data type (data fetched from prisma/postgres)
tried to use superjson as a solution for this issue https://github.com/vercel/next.js/issues/11993, as suggested in https://github.com/blitz-js/superjson#using-with-nextjs

unfortunatly ran into issue with serialization of the Decimal data type as shown by the below error:

image

would be great if superjson supported this? or am I doing something wrong?

I'd rather not resort to have to using maps as shown in this fix https://github.com/prisma/prisma-examples/issues/3047 and our current fallback of `JSON.parse(JSON.stringify(result)` is somewhat inefficient I imagine

### PR DESCRIPTION
**Pull request by michaeljonsampson**
Allows using Prisma Decimal type in getServerSideProps.
This fixes #152

### CODE REVIEW

**Comment by Skn0tt** [comment]
Hi @michaeljonsampson! Thanks for opening this PR. When you opened the issue, I somehow thought that `Decimal` was a built-in type like `BigInt`. It's apparently a proposal in Stage 1: https://github.com/tc39/proposal-decimal

To keep bundle size down, SuperJSON needs to stay as lean as possible. I've adapted your changes into #159, which adds a test for Decimal.js and mentions how to integrate in the README.

**Comment by michaeljonsampson** [comment]
@Skn0tt wasn't my issue but I ran into the same problem an came across it. Didn't know about `registerCustom`. That covers my use case. Tested #159 and I can still serialize Prisma.Decimal. Thanks.

**Comment by michaelhays** [comment]
Just a heads up for anyone using superjson with [tRPC Data Transformers](https://trpc.io/docs/data-transformers), make sure to put the [Decimal.js `registerCustom` recipe](https://github.com/blitz-js/superjson#decimaljs--prismadecimal) in both your [client](https://trpc.io/docs/data-transformers#2-add-to-createtrpcclient-or-withtrpc-config) (`pages/_app.tsx`) and [router](https://trpc.io/docs/data-transformers#3-add-to-your-approuter) (`routers/_app.ts`)!

**Comment by michealroberts** [comment]
Hi @michaelhays ... do you have a minimal reproduction of your superjson transformer with decimal.js support? I'd love to use it one of our projects ...

**Comment by michaelhays** [comment]
Sure, here are the relevant files for a Next.js project:

<details>
<summary>src/utils/superjson.ts</summary>

```ts
import Decimal from 'decimal.js'
import superjson from 'superjson'

superjson.registerCustom<Decimal, string>(
  {
    isApplicable: (v): v is Decimal => Decimal.isDecimal(v),
    serialize: (v) => v.toJSON(),
    deserialize: (v) => new Decimal(v),
  },
  'decimal.js',
)

export default superjson
```

(Or, if using Prisma, be sure to use `Prisma.Decimal` everywhere)

```ts
import { Prisma } from '@prisma/client'
import superjson from 'superjson'

superjson.registerCustom<Prisma.Decimal, string>(
  {
    isApplicable: (v): v is Prisma.Decimal => Prisma.Decimal.isDecimal(v),
    serialize: (v) => v.toJSON(),
    deserialize: (v) => new Prisma.Decimal(v),
  },
  'decimal.js',
)

export default superjson
```
</details>

<details>
<summary>src/utils/trpc.ts</summary>

```ts
import type { AppRouter } from '@/server/appRouter'
import { createTRPCNext } from '@trpc/next'
import superjson from './superjson'

export const trpc = createTRPCNext<AppRouter>({
  config() {
    return {
      transformer: superjson,
      links: [...],
    }
  },
})
```
</details>

<details>
<summary>src/server/trpc.ts</summary>

```ts
import { initTRPC, TRPCError } from '@trpc/server'
import superjson from '../utils/superjson'
import type { Context } from './context'

const t = initTRPC.context<Context>().create({ transformer: superjson })

export const publicProcedure = t.procedure
```
</details>

**Comment by AmruthPillai** [comment]
Thank you for the code examples. The workaround for Decimal.js works with trpc, but how do I register custom when using it with the next-superjson-plugin (swc)? I'm unable to pass Decimal properties as props from a Server Component to a Client Component.

**Comment by Skn0tt** [comment]
You need to execute the `registerCustom` call is on both the client and the server. I‘m unsure what the right files for that are in Next.js nowadays - maybe something like `app.server.js` and `app.client.js`, if they exist? Let us know what works for you, i‘m sure this is super useful for many folks.

**Comment by AmruthPillai** [comment]
Yes, I did try this. I added the registerCustom function on the server component level (at layout.tsx) and inside a client component (inside a useEffect of a ClientComponent and outside). Adding it to the client component seemed to do nothing, but adding it on the server component threw the same error.

I'm not sure if there's a way to run a function before the build even begins, with either webpack or SWC, that might be a good place to add this.

**Comment by pedro757** [comment]
Did you find a solution?

@AmruthPillai

**Comment by AmruthPillai** [comment]
Nope, just reverted back to using `Number` datatype in Prisma for now. Would love to make use of Decimal, but I believe this is something Next.js needs to get straight, adding middlewares for client and server individually, and not just a single Edge runtime variant.

**Comment by pedro757** [comment]
I was able to make it work, setting the `registerCustom` in a `page.tsx` and in passing `data-superjson` prop to client component

<details>
  <summary>See the Code</summary>

  ### Server Component
  ```tsx
import { Temporal } from "temporal-polyfill";
import Button from "./client";
import SuperJSON from "superjson";
import PlainDate, { startOfMonth, weekNumber } from 'plain-date'
SuperJSON.registerCustom<Temporal.PlainDate, string>(
  {
    isApplicable: (v): v is Temporal.PlainDate =>
      v instanceof Temporal.PlainDate ||
      (typeof v === "string" &&
        RegExp(
          /^(19[0-9]{2}|2[0-9]{3})-(0[1-9]|1[012])-([123]0|[012][1-9]|31)$/,
        ).test(v)),
    serialize: (v) => v.toJSON(),
    deserialize: (v) => Temporal.PlainDate.from(v),
  },
  "PlainDate",
)

new PlainDate("2023-01-01")

export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <Button date={new Temporal.PlainDate(2023, 1, 1)} data-superjson />
    </main>
  );
}

  ```

</details>

With that I receive my custom type in the client component

@AmruthPillai

**Pull request closed without merging**
