### PR TITLE
Implement custom type checking

### PR DESCRIPTION
**Pull request by merelinguist**
It turns out that `@sindresorhus/is` is actually quite big! Right now it accounts for 64% of our [bundle size](https://bundlephobia.com/result?p=superjson@1.0.1). This is because it provides much more functionality than we actually need–we only use a handful of `is.whatever` functions. I’ve therefore written a custom type-checking util which should be much more lightweight. This also means we can brag about having zero external dependencies 😄.

### CODE REVIEW

**Comment by flybayer** [comment]
Unused stuff should tree-shake out if you do this 🤔 

```ts
import {map as isMap} from '@sindresorhus/is
```

**Comment by merelinguist** [comment]
@flybayer No expert here but I think the problem is that it doesn’t have any named exports–just one big `is` function. So we can’t import functions individually like that.

**Comment by Skn0tt** [comment]
Good catch on the bundle size! I'd like to have a look into wether it's really impossible to tree-shake `@sindresorhus/is` though - it looks like it should be. The Bundlephobia link says `This package exports ES6 modules, but isn't marked side-effect free.` on the bottom, which makes me think it's a problem on our side 🙈

On "brag about having zero external dependencies": I see where you're coming from, but this is a very generic problem which I don't feel we should reinvent. Personally, I'd prefer using smth battle-proof instead of rolling our own here.

**Comment by merelinguist** [comment]
@Skn0tt If you can find a way to fix the bundle size using `@sindresorhus/is` then I’m happy to continue using it. :) Either way, as indicated by brevity of the code I’ve added, this is a relatively simple problem, so it definitely shouldn’t be such a large part of our bundle size.

**Comment by Skn0tt** [comment]
Will have a look into the tree shaking part.

When I saw `Object.prototype.toString.call`, I guess I was kinda scared of users breaking this by doing wonky stuff with prototype chains etc. So I guess I'm not really concerned about bundle size, but rather about maintaining it - I don't know anything about the whole prototype chain stuff ...

**Comment by Skn0tt** [comment]
Alright, I'm dumb. `@sindresorhus/is` [does exactly the same...](https://github.com/sindresorhus/is/blob/e31db97eab467f2c180c857dd7474accf8ac2215/source/index.ts#L87).

**Pull request merged**
