### PR TITLE
Remove lodash dep

### PR DESCRIPTION
**Pull request by KATT**
- Importing lodash for one line of code seems a bit excessive
- Let the TypeScript compiler handle compatability rather than restricting you to write legacy-style code #63

### CODE REVIEW

**Review by Skn0tt — COMMENTED** [review]
I like the thought of going dependency-less. Actually, SuperJSON didn't have any dependencies until https://github.com/blitz-js/superjson/issues/62 - TypeScript didn't seem to compile down the code as expected, so we added Lodash instead.

`target` [defaults to `es3`](https://www.typescriptlang.org/tsconfig#target), so you actually increased our deployment target to `es5`. This doesn't seem right for maintaining compatibility. What am I missing?

Having said that, maybe we should just throw out `lodash` and write that `_.find` ourselves. Not that complex 😅

**Comment by KATT** [comment]
I actually don't know, I assumed default `target` was higher. TS should already do this work for you.

Re https://www.typescriptlang.org/tsconfig#target
> The target setting changes which JS features are downleveled and which are left intact. For example, an arrow function () => this will be turned into an equivalent function expression if target is ES5 or lower.

I mean, you use `Symbol` which is an ES6-thing, so if TS doesn't fix that it's already broken, isn't it?

**Comment by KATT** [comment]
I actually realised that the test results is a false-positive though as there is lodash referneces elsewhere that I missed, so will update those.

**Comment by KATT** [comment]
It seems that error was just that `fromEntries` - https://caniuse.com/?search=fromEntries

**Comment by KATT** [comment]
Fuck it, I'll just close this, too much hassle to change.

**Pull request closed without merging**
